import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import PokeMenu from './components/poke-menu/poke-menu';
import './globals.css';

const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '600', '700'],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: 'PokeDex',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning={true}>
      <body className={`${openSans.variable} antialiased`}>
        <PokeMenu />
        {children}
      </body>
    </html>
  );
}
